#Python Tutorial With Google Colab 한글번역

이 튜토리얼은 [Justin Johnson] (https://web.eecs.umich.edu/~justincj/)이 cs231n 강의용으로 작성했습니다. [Volodymyr Kuleshov](http://web.stanford.edu/~kuleshov/) 및 [Isaac Caswell](https://symsys.stanford.edu/viewing/symsysaffiliate/21335)이 cs228 수업용 Jupyter 노트북으로 각색하였고, [cs231n](https://cs231n.github.io/)의 2020년 봄 버전을 위해 Kevin Zakka가 Colab에 맞게 조정했습니다. 기본적으로 Python3을 실행합니다. 영상처리와 딥러닝 강의을 위해
 한글 번역을 진행했습니다.

##Introduction

Python은 그 자체로도 훌륭한 범용 프로그래밍 언어이지만, 인기있는 라이브러리 (numpy, scipy, matplotlib) 덕분에 과학 컴퓨팅을 위한 강력한 환경을 제공하기도 합니다.  

많은 분들이 Python과 numpy에 대한 경험이 있으실 것으로 기대합니다. 나머지분을 위해 이 섹션은 Python 프로그래밍 언어와 과학 컴퓨팅을 위한 Python 사용에 대한 빠른 집중 과정을 제공합니다.

여러분 중 일부는 Matlab에 대한 사전 지식이있을 수 있습니다.이 경우 Matlab 사용자를 위한 [페이지](https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html) 도 권장합니다. ).

이 튜토리얼에서는 다음을 다룹니다.

* 기본 Python : 기본 데이터 유형 (컨테이너, 목록, 사전, 집합, 튜플), 함수, 클래스
* Numpy : 배열, 배열 인덱싱, 데이터 유형, 배열 수학, 방송
* Matplotlib : 플로팅, 서브 플롯, 이미지
* IPython : 노트북 만들기, 일반적인 워크 플로

## A Brief Note on Python Versions

2020 년 1 월 1 일부터 Python은`python2`에 대한 지원을 [공식적으로 중단](https://www.python.org/doc/sunset-python-2/)했습니다. 따라서 우리는 수업을 위해 Python 3.7을 사용할 것입니다. `python --version`을 실행하여 명령 줄에서 Python 버전을 확인할 수 있습니다. Colab에서는`Runtime-> Change Runtime Type`을 클릭한 뒤 `python3`을 선택하여 Python 버전을 적용 할 수 있습니다. 2020 년 4 월부터 Colab은 오류없이 모든 것을 실행할 수 있는 Python 3.6.9를 사용합니다.

In [1]:
!python --version

Python 3.10.12


##Basics of Python

Python은 동적으로 입력되는 고수준의 다중 패러다임 프로그래밍 언어입니다. Python 코드는 매우 읽기 쉬우면서도 몇 줄의 코드로 매우 강력한 아이디어를 표현할 수 있기 때문에 의사 코드(pseudo-code)와 비슷하다고합니다. 예를 들어, 다음은 Python에서 고전적인 퀵 정렬(quick-sort) 알고리즘을 구현 한 것입니다.

In [2]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


###Basic data types

####Numbers

정수(integer)와 부동 소수점(floats)은 다른 프로그래밍 언어에서와 같이 동작합니다.

In [3]:
x = 3
print(x, type(x))

3 <class 'int'>


In [4]:
print(x + 1)   # Addition
print(x - 1)   # Subtraction
print(x * 2)   # Multiplication
print(x ** 2)  # Exponentiation

4
2
6
9


In [5]:
x += 1
print(x)
x *= 2
print(x)

4
8


In [6]:
y = 2.5
print(type(y))
print(y, y + 1, y * 2, y ** 2)

<class 'float'>
2.5 3.5 5.0 6.25


많은 언어와 달리 Python에는 단항 증가 (x ++) 또는 감소 (x--) 연산자가 없습니다.

파이썬은 또한 긴 정수와 복소수를 위한 내장형 타입을 가지고 있습니다. 자세한 내용은 [문서](https://docs.python.org/3.7/library/stdtypes.html#numeric-types-int-float-long-complex)에서 확인할 수 있습니다.

####Booleans

파이썬은 이항 논리에 대한 모든 일반적인 연산자를 제공하며, 연산 기호 (`&&`,`||`등) 대신 영어 단어를 사용합니다.

In [7]:
t, f = True, False
print(type(t))

<class 'bool'>


이항 연산자에 대해 살펴봅니다.

In [8]:
print(t and f) # Logical AND;
print(t or f)  # Logical OR;
print(not t)   # Logical NOT;
print(t != f)  # Logical XOR;

False
True
False
True


####문자열(Strings)

In [9]:
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter
print(hello, len(hello))

hello 5


In [10]:
hw = hello + ' ' + world  # String concatenation
print(hw)

hello world


In [11]:
hw12 = '{} {} {}'.format(hello, world, 12)  # string formatting
print(hw12)

hello world 12


문자열 객체에는 유용한 메서드가 많이 있습니다. 예를 들면 :

In [12]:
s = "hello"
print(s.capitalize())  # Capitalize a string
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces
print(s.center(7))     # Center a string, padding with spaces
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another
print('  world '.strip())  # Strip leading and trailing whitespace

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


[documentation](https://docs.python.org/3.7/library/stdtypes.html#string-methods)에서 모든 문자열 메소드 목록을 찾을 수 있습니다.

###Containers

Python에는 리스트, 딕셔너리(dictionaries), 셋(sets) 및 튜플과 같은 몇 가지 기본 제공 컨테이너 유형이 포함되어 있습니다.

####Lists

List는 Python의 배열에 해당하는 요소이며, 크기를 조정할 수 있고 다양한 유형의 요소를 포함 할 수 있습니다.

In [13]:
xs = [3, 1, 2]   # Create a list
print(xs, xs[2])
print(xs[-1])     # Negative indices count from the end of the list; prints "2"

[3, 1, 2] 2
2


In [14]:
xs[2] = 'foo'    # Lists can contain elements of different types
print(xs)

[3, 1, 'foo']


In [15]:
xs.append('bar') # Add a new element to the end of the list
print(xs)

[3, 1, 'foo', 'bar']


In [16]:
x = xs.pop()     # Remove and return the last element of the list
print(x, xs)

bar [3, 1, 'foo']


[문서](https://docs.python.org/3.7/tutorial/datastructures.html#more-on-lists)에서 리스트에 대한 모든 세부 정보를 찾을 수 있습니다.

####Slicing

한 번에 하나씩 목록 요소에 액세스하는 것 외에도 Python은 서브리스트(sublist)를 이용하기 위한 간결한 구문을 제공합니다. 이를 슬라이싱이라고합니다.

In [17]:
nums = list(range(5))    # range is a built-in function that creates a list of integers
print(nums)         # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])      # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print(nums[:-1])    # Slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4] = [8, 9] # Assign a new sublist to a slice
print(nums)         # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


####Loops

다음과 같이 리스트의 요소를 반복 할 수 있습니다.

In [18]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

cat
dog
monkey


For 루프 각 요소의 index를 이용하려면 `enumerate` 내장 함수를 사용하세요.

In [19]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#{}: {}'.format(idx + 1, animal))

#1: cat
#2: dog
#3: monkey


####List comprehensions:


프로그래밍 할 때 종종 우리는 한 유형의 데이터를 다른 유형으로 변환하려고 합니다. 간단한 예로 제곱수를 계산하는 다음 코드를 살펴보십시오.

In [20]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)

[0, 1, 4, 9, 16]


List comprehension은 파이썬의 독특한 문법으로써, 위의 코드를 다음과 같이 간단하게 만들 수 있습니다:

In [21]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

[0, 1, 4, 9, 16]


또한 List comprehensions은 조건문을 안에 넣을 수 있습니다:

In [22]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

[0, 4, 16]


####Dictionaries

Dictionary는 Java의`Map` 또는 Javascript의 object와 유사한 (key, value) 쌍을 저장합니다. 다음과 같이 사용할 수 있습니다.

In [23]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"

cute
True


In [24]:
d['fish'] = 'wet'    # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"

wet


In [26]:
print(d['monkey'])  # KeyError: 'monkey' not a key of d

KeyError: ignored

In [27]:
print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"

N/A
wet


In [30]:
del d['fish']        # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

KeyError: ignored

자세한 내용은 [문서](https://docs.python.org/2/library/stdtypes.html#dict) 를 참고하십시오.

다음과 같이 Dictionary의 key를 반복순회(iterate)할 수 있습니다.

In [28]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A {} has {} legs'.format(animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


Dictionary comprehensions: list comprehensions과 비슷합니다. 다음과 같은 방법으로 dictionary를 구성할 수 있습니다.

In [29]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)

{0: 0, 2: 4, 4: 16}


####Sets

집합(sets)은 순서가 지정되지 않은 고유 한 요소의 모음입니다. 간단한 예로서 다음을 보세요.

In [31]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"


True
False


In [32]:
animals.add('fish')      # Add an element to a set
print('fish' in animals)
print(len(animals))       # Number of elements in a set;

True
3


In [33]:
animals.add('cat')       # Adding an element that is already in the set does nothing
print(len(animals))
animals.remove('cat')    # Remove an element from a set
print(len(animals))

3
2


_Loops_ : 집합을 반복하는 것은 목록을 반복하는 것과 동일한 구문을 갖습니다. 그러나 집합은 순서가 지정되지 않았기 때문에 집합의 요소를 방문하는 순서를 미리 알 수 없습니다.

In [34]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#{}: {}'.format(idx + 1, animal))

#1: dog
#2: cat
#3: fish


Set comprehensions: 앞에서 보았던 lists와 dictionaries 처럼, sets도 유사한 comprehensions 문법을 제공합니다.

In [35]:
from math import sqrt
print({int(sqrt(x)) for x in range(30)})

{0, 1, 2, 3, 4, 5}


####Tuples

튜플은 변하지 않도록 (immutable) 정렬 된 값 목록입니다. 튜플은 여러면에서 목록과 유사합니다. 가장 중요한 차이점 중 하나는 튜플을 사전의 키와 집합의 요소로 사용할 수 있지만 리스트는 사용할 수 없다는 것입니다. 다음은 간단한 예입니다.

In [36]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)       # Create a tuple
print(type(t))
print(d[t])
print(d[(1, 2)])

<class 'tuple'>
5
1


In [38]:
t[0] = 1

TypeError: ignored

###Functions

파이썬 함수는`def` 키워드를 사용하여 정의됩니다. 예를 들면 :

In [39]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


우리는 종종 다음과 같이 선택적 키워드 인수를 받는 함수를 정의합니다.

In [ ]:
def hello(name, loud=False):
    if loud:
        print('HELLO, {}'.format(name.upper()))
    else:
        print('Hello, {}!'.format(name))

hello('Bob')
hello('Fred', loud=True)

###Classes

Python에서 클래스를 정의하는 문법은 다음과 같이 직관적입니다.

In [ ]:
class Greeter:

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
          print('HELLO, {}'.format(self.name.upper()))
        else:
          print('Hello, {}!'.format(self.name))

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

##Numpy

Numpy는 Python의 과학 컴퓨팅을 위한 핵심 라이브러리입니다. 고성능 다차원 배열 개체와 배열 작업을 위한 도구를 제공합니다. 이미 MATLAB에 익숙하다면이 [튜토리얼](http://wiki.scipy.org/NumPy_for_Matlab_Users)이 Numpy를 시작하는 데 유용 할 것입니다.

Numpy를 사용하려면 먼저`numpy` 패키지를 가져와야 합니다.

In [ ]:
import numpy as np

###Arrays

numpy 배열은 모두 동일한 유형의 값의 그리드(grid)이며 음이 아닌 정수의 튜플에 의해 인덱싱됩니다. 차원의 수(the number of dimensions)는 배열의 랭크(rank)입니다. 배열의 모양(shape)은 각 차원을 따라 배열의 크기를 제공하는 정수의 튜플입니다.

Python 리스트를 통해서 numpy 배열을 초기화하고 대괄호\[, \]를 사용하여 요소에 액세스 할 수 있습니다.

In [ ]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)

In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

In [ ]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

Numpy는 또한 배열을 만드는 다양한 방법을 제공합니다.

In [ ]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

In [ ]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

In [ ]:
c = np.full((2,2), 7) # Create a constant array
print(c)

In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

e = np.random.random((2,2)) # Create an array filled with random values
print(e)

###Array indexing

Numpy는 배열로 인덱싱하는 여러 가지 방법을 제공합니다.

슬라이싱 : Python 목록과 유사하게 numpy 배열을 슬라이스 할 수 있습니다. 배열은 다차원 일 수 있으므로 배열의 각 차원에 대해 슬라이스를 지정해야합니다.

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

배열의 슬라이스는 동일한 데이터에 대한 view이므로, 이를 수정하면 원래 데이터가 속한 배열이 수정됩니다.

In [ ]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])

정수 인덱싱과 슬라이스 인덱싱을 혼합 할 수도 있습니다. 그러나 이렇게하면 원래 배열보다 낮은 랭크의 배열이 생성됩니다. (MATLAB이 배열 슬라이싱을 처리하는 방식과는 상당히 다름)

In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

배열의 중간 행에있는 데이터에 액세스하는 두 가지 방법이 있습니다.
정수 인덱싱을 슬라이스와 혼합하면 더 낮은 랭크의 배열이 생성됩니다.
슬라이스만 사용하면 다음과 같은 랭크의 배열이 생성됩니다.
아래 예시를 참고하시오.

In [ ]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

In [ ]:
# 배열의 컬럼에 액세스할때도 동일한 구분방법을 사용할 수 있습니다.
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

정수 배열 인덱싱 : 슬라이싱을 사용하여 numpy 배열로 인덱싱하면 결과는 항상 원래 배열의 하위 배열이됩니다. 반대로 정수 배열 인덱싱을 사용하면 다른 배열의 데이터를 사용하여 임의의 배열을 구성 할 수 있습니다. 다음 예시를 보십시오.

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

# 정수 배열 인덱싱 예시
# 리턴 배열값은 shape (3,)을 갖는다
print(a[[0, 1, 2], [0, 1, 0]])

# 위의 예시는 아래의 예시와 같다:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

In [ ]:
# 정수 배열 인덱싱을 사용하면, 원본 출처 배열에서
# 동일한 값을 다시 사용할 수 있다.
print(a[[0, 0], [1, 1]])

# 위와 아래의 예시는 동일한 결과를 갖는다.
print(np.array([a[0, 1], a[0, 1]]))

정수 배열 인덱싱의 유용한 트릭 중 하나는 행렬의 각 행에서 하나의 요소를 선택하거나 변경하는 것입니다.

In [ ]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

In [ ]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

In [ ]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

부울 배열 인덱싱 (Boolean array indexing) : 부울 배열 인덱싱을 사용하면 배열의 임의 요소를 선택할 수 있습니다. 종종 이러한 유형의 인덱싱은 특정 조건을 충족하는 배열 요소를 선택하는 데 사용됩니다.

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

In [ ]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

더 많은 numpy 배열 인덱싱이 있지만 본 문서에는 많은 부분이 생략되었습니다. 더 많은 정보는 numpy documentation을 참조하세요.

###Datatypes

모든 numpy 배열은 동일한 유형의 요소 그리드입니다. Numpy는 배열을 구성하는 데 사용할 수있는 대규모 numeric datatypes를 제공합니다. Numpy는 배열을 만들 때 데이터 유형을 예측하려고 하지만 일반적으로 데이터 유형을 명시적(explicitly)으로 지정하는 인수(optional argument)도 포함할 수 있습니다.

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

[문서](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html)에서 numpy 데이터 유형에 대한 모든 내용을 찾을 수 있습니다.

###Array math

기본 수학 함수는 배열의 요소 별로 작동하며, 연산자 오버로드와 numpy 모듈의 함수형태 모두 사용할 수 있습니다.

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

In [ ]:
# Elementwise square root(루트); produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

`*`는 행렬 곱셈이 아니라 요소 별(element-wise) 곱셈입니다. 대신 dot 함수를 사용하여 벡터의 내적을 계산할 수 있습니다. dot은 numpy 모듈의 함수와 배열 객체의 인스턴스 메소드로 모두 사용할 수 있습니다.

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

numpy의`dot` 연산자와 동일한`@`연산자를 사용할 수도 있습니다.

In [ ]:
print(v @ w)

In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

Numpy는 배열에서 계산을 수행하는 데 유용한 많은 기능을 제공합니다. 가장 유용한 것은 배열의 총합을 구하는 `sum`입니다.

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

[문서](http://docs.scipy.org/doc/numpy/reference/routines.math.html)에서 numpy가 제공하는 수학 함수의 전체 목록을 찾을 수 있습니다.

배열을 사용하여 수학 함수를 계산하는 것 외에도 배열의 데이터를 변형하거나 조작해야할 경우가 많습니다. 이러한 유형의 작업의 간단한 예는 행렬을 전치(transpose)하는 것입니다. 행렬을 전치하려면 배열 객체의 T 속성을 사용하면 됩니다.

In [ ]:
print(x)
print("transpose\n", x.T)

In [ ]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

###Broadcasting

브로드 캐스팅은 numpy가 산술 연산을 수행 할 때 다양한 모양의 배열로 작업 할 수 있도록하는 강력한 메커니즘입니다. 종종 우리는 더 작은 배열과 더 큰 배열을 가지고 있으며, 더 큰 배열에서 일부 작업을 수행하기 위해 더 작은 배열을 여러 번 사용하려고합니다.

예를 들어 행렬의 각 행에 아래와 같은 상수 벡터를 추가한다고 가정합시다.

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

위 코드는 문제가 없습니다만, 행렬 'x'가 매우 크면 Python에서 명시 적 루프를 계산하는 속도가 느릴 수 있습니다. 행렬 'x'의 각 행에 벡터 v를 추가하는 것은 'v'의 여러 복사본을 세로로 쌓은 'vv'를 만들고, 'x'와 'vv'의 요소 별 합산을 수행하는 것과 같습니다.

이는 다음과 같이 구현할 수 있습니다.

In [ ]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

In [ ]:
y = x + vv  # Add x and vv elementwise
print(y)

Numpy 브로드 캐스팅을 사용하면 v의 여러 복사본을 실제로 만들지 않고도 위 계산을 수행 할 수 있습니다.

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

`y = x + v` 코드 라인은 브로드캐스팅으로 인해 `x`의 모양이`(4, 3)`이고`v`가`(3,)`인 경우에도 작동합니다. 여기서는 v가 실제로 모양이`(4, 3)`인 것처럼 동작합니다.

위 설명이 부족하다면 [문서](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) 또는 이 [explanation] (http://wiki.scipy.org/EricsBroadcastingDoc)에서 부가 설명을 읽어보십시오.

브로드캐스팅을 지원하는 함수를 범용 함수라고합니다. 모든 범용 함수 목록은 [문서](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs)에서 찾을 수 있습니다.

다음은 브로드캐스팅의 몇 가지 응용입니다.

In [ ]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

In [ ]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

In [ ]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

In [ ]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

브로드 캐스팅은 일반적으로 코드를 더 간결하고 빠르게 만들어 주므로, 가능한한 최대한 사용하도록 노력해야 합니다.

이 간략한 개요는 numpy에 대해 알아야 할 많은 중요한 사항을 다루었지만 빠진 부분도 많습니다. numpy에 대한 자세한 내용은 [numpy 참조](http://docs.scipy.org/doc/numpy/reference/)를 확인하세요.

##Matplotlib

Matplotlib는 플로팅 라이브러리입니다. 이 섹션에서는 MATLAB과 유사한 플로팅 시스템을 제공하는`matplotlib.pyplot` 모듈에 대해 간략하게 소개합니다.

In [ ]:
import matplotlib.pyplot as plt

이 special iPython 명령어을 실행하여 플롯을 인라인으로 표시합니다.

In [ ]:
%matplotlib inline

###Plotting

'matplotlib'에서 가장 중요한 기능은 2D 데이터를 그릴 수있는 plot입니다. 다음은 간단한 예입니다.

In [ ]:
# Compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

# Plot the points using matplotlib
plt.plot(x, y)

약간의 추가 작업으로 한 번에 여러 줄을 쉽게 그릴 수 있고 제목, 범례 및 축 레이블을 추가 할 수 있습니다.

In [ ]:
y_sin = np.sin(x)
y_cos = np.cos(x)

# matplotlib를 이용하여 점들을 그려서 보여준다.
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])

###Subplots

subplot 함수를 사용하여 동일한 Figure에 subfigure들을 그릴수 있습니다.

In [ ]:
# x값에 따른 코싸인과 싸인 함수를 계산한다.
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# 높이가 2 너비가 1인 subplot를 만들고,
# 첫번째 sub플롯을 활성화 한다.
plt.subplot(2, 1, 1)

# 첫번째 플롯을 그린다.
plt.plot(x, y_sin)
plt.title('Sine')

# 두번째 sub플롯을 활성화 한 후 플롯을 그린다.
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')

# figure를 보여준다.
plt.show()

[documentation](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.subplot)에서`subplot` 기능에 대한 자세한 내용을 읽을 수 있습니다.

# 마지막 연습하기

**코드 분석 및 결과 예측은 단순히 눈으로 훑어보는 것 이상의 좋은 학습 효과를 갖습니다. Colab의 수정 메뉴의 최하단에 '수정 --> 모든 출력 지우기' 항목이 있습니다. 지금까지 진행한 실습내용 출력을 모두 지우고, 모든 항목의 코드에 따라 print출력 결과를 예측해서 시험문제처럼 직접 풀어보시길 바랍니다. 향후 과제 해결을 위해 큰 도움이 될 것 입니다.**